version: '3'

services:
  traefik:
    image: traefik:1.6.5
    #restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik/ppdb.traefik.toml}:/traefik.toml
      #- ${ACME_JSON:-./traefik/acme.json}:/acme.json
    labels:
      - "traefik.enable=false"
      - "traefik.port=8080"
      - ${TRAEFIK_URL_CONFIG:-traefik.frontend.rule=Host:traefik.docker.localhost}

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/conf.d:/conf.d
      - ./data:/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - default # postgres datasource grafana
      - pgnet

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    expose:
      - "80"
#    ports:
#      - "5050:80"
    networks:
      - pgnet
    volumes:
      - ./pgadmin:/root/.pgadmin
    labels:
      - "traefik.backend=naturalis-pgadmin"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=80"
      - ${GRAFANA_URL_CONFIG:-traefik.frontend.rule=Host:pgadmin.ppdb.naturalis.nl}

  python:
    build: ./python
    command: python -m http.server 8000
    depends_on:
      - postgres
    volumes:
      - ./python/script:/usr/src/app
      - ./python/logs:/var/log/app
      - ./data:/data
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}@${POSTGRES_PASSWORD}/${POSTGRES_DB}"
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_DB: ${POSTGRES_DB}
      DATABASE_HOST: ${POSTGRES_HOST}
    networks:
      - default # postgres datasource grafana
      - pgnet

networks:
  pgnet:
    external: true
  web:
    external: true

volumes:
  pglog:
  pgdata:
