version: '3'

services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/conf.d:/conf.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REPLICATION_USER=${REPLICATION_USER}
      - REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
    networks:
      - default # postgres datasource grafana
      - pgnet
  python:
    build: ./python
    command: python -m http.server 8000
    depends_on:
      - postgres
    volumes:
      - ./python/script:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}@${POSTGRES_PASSWORD}/${POSTGRES_DB}"
    networks:
      - default # postgres datasource grafana
      - pgnet

networks:
  pgnet:
    external: true

volumes:
  pglog:
  pgdata:
